#This is where the database login info is stored.
#!TODO PREDEPLOY: configure this to work with the deployment database.

development:
  adapter: mysql2
  database: alphamycba
  host: localhost
  username: pooky
  password: 'DELTA5+quebec'