# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

ActionItem.create([
  { :createdByID => 1, :isApproved => true, :created_at => "2013-11-11 22:22:09", :updated_at => "2013-11-11 22:22:55", :itemType => "news" }
], :without_protection => true )



CalendarItem.create([
  { :actionItemID => nil, :calendarText => nil, :calendarDate => nil, :created_at => nil, :updated_at => nil, :title => nil }
], :without_protection => true )



CollegeAdmins.create([
  { :userID => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



CommunicationsUser.create([
  { :userID => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



DepartmentAdmins.create([
  { :created_at => nil, :updated_at => nil }
], :without_protection => true )



FacultyProfile.create([
  { :currentResearch => "Space", :education => "Oxford", :honors => "Medal of Honor", :created_at => "2013-11-08 19:43:55", :updated_at => "2013-11-11 22:21:25", :permalink => "professor_test", :bodyText => "Likes Things" }
], :without_protection => true )



FacultyUser.create([
  { :userID => 2, :facultyProfileID => 2, :userPictureID => 2, :created_at => "2013-11-08 19:43:55", :updated_at => "2013-11-08 19:43:55" }
], :without_protection => true )



NewsItem.create([
  { :actionItemID => 9, :newsText => "Indeed they did.", :created_at => "2013-11-11 22:22:10", :updated_at => "2013-11-11 22:22:10", :title => "Things happened" }
], :without_protection => true )



Publication.create([
  { :facultyUserID => nil, :publicationText => "Glynn, RD. 1999. Duking it out: the story of a Morro Bay power plant. In: Bush GW, Davis, JG, editors. Energy and crisis: the dialectic of electricity in California. Sacramento: Ampere Press. p 35-78.", :created_at => "2013-11-12 20:49:40", :updated_at => "2013-11-12 20:49:40" }
], :without_protection => true )



User.create([
  { :email => "danearing@gmail.com", :godBit => true, :firstName => "Dave", :lastName => "Nearing", :created_at => "2013-11-04 19:49:55", :updated_at => "2013-11-04 19:49:55", :password_digest => "$2a$10$F8/.xFMJQAosJYiDHVEJBO2ZrdC9x6L6X7a6f4/o/P1IpnJtY8yTK", :isSuperUser => nil, :isGenericUser => true, :isFacultyUser => nil, :isCommunicationsUser => nil, :phoneNumber => nil },
  { :email => "test@gmail.com", :godBit => nil, :firstName => "test", :lastName => "professor", :created_at => "2013-11-08 19:43:55", :updated_at => "2013-11-08 19:43:55", :password_digest => "$2a$10$hhE4Bb8TwMcGla7i7Z0cTunczRfRhWDggVUj6xVcKhkJ5YhPEqOpO", :isSuperUser => nil, :isGenericUser => nil, :isFacultyUser => true, :isCommunicationsUser => nil, :phoneNumber => "1234567890" },
  { :email => "fstewart@cba.ua.edu", :godBit => nil, :firstName => "Freddie", :lastName => "Stewart", :created_at => "2013-11-11 22:20:43", :updated_at => "2013-11-11 22:20:43", :password_digest => "$2a$10$x4gMUlg1yKGeJBwBgbtmwejJkAp3Rb0yXRsqhfvYgromMFDR.l0lK", :isSuperUser => nil, :isGenericUser => nil, :isFacultyUser => false, :isCommunicationsUser => nil, :phoneNumber => "1234567890" }
], :without_protection => true )



UserPicture.create([
  { :userID => nil, :picturePath => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


